### PR TITLE
Refactoring:  using zeep module

### PR DESCRIPTION
**Pull request by spalk**
I started using zeep module for generating SOA requests. Now you don't have to deal with xml-patterns because it do all work for you. You need just set service name (for WSDL URL), call action and pass parameters.   As a result you get a data structure object (lists and dics), so you don't need to parse anything. Meiner Meinung nach, das ist wunderschön!  :)
It also fix a headache with session when you have to pass token in every single request header.

### CODE REVIEW

**Comment by BernsiD** [comment]
Hi Dmitry,
Thank that is really wunderschön :). Thank you very much for sharing and contributing. Best Regards Bernhard

**Comment by BernsiD** [comment]
Hi Dmitry, Does the zeep implementation work for you? I just tested and i am getting server errors. Maybe zeep cannot handle the envelopes if there are not all optional fields given a value? i will investigate further, maybe it is failure on my side

**Comment by spalk** [comment]
Hi Bernhard, 

For me zeep works fine. It can handle requests wihout optional fields and if some required variable was not passed, it shows its name (in error message). 
You should only pass parameters not as a plain list, but as a data structure according to wsdl, for instance: 
`response = client.service.getItemFromId(nRev=1, infos={'itemId':item_id, 'revIds':rev_id}, pref='')`
Try different requests, in which you sure how they work. 

The only problem I had with zeep was empty responses from server (with code 200 though). I solved it with disabling xml-declaration in requests (by a little customizing zeep Transport  class). I'm not sure was it problem of zeep or my server. 

Hope it will work for you.

**Comment by BernsiD** [comment]
Hi Dmitry,

I tried, but somehow i can't get it to work. All i managed was to get the login, but every other soa requests fails with zeep.exceptions.Fault: Message:Unknown Server Exception even the set policy request. Can it be related to the Teamcenter Version? I am using 12.2.0.11 atm. I really would love to get this to work cause i think your solution is super sophisticated.

**Comment by spalk** [comment]
Hi Bernhard,

Your code worked for me, so, even if our TC server versions are different, I don't think it's realated to it.  More likely there is some mistake somewhere.  Be sure you pass Transport object while creating Client object in all following requersts after login, because it containts session informaiton. Otherwise such requests will be unauthorized and denied by server. 

I make a small one-file-script (without any flask functionality) just to test zeep.  It should: 
- login to server;
- change policy;
- get item information by part_id and revision;
- logout.
Fill your credentials and item id and revision at the top of the file and try it out. 

```python
from zeep import Client
from zeep.transports import Transport
from lxml import etree
from requests import Session


# Credentials
TC_HOST = 'http://your_server:7001/tc/services'
TC_LOGIN = 'your_login'
TC_PASSWORD = 'your_password'

# Test item details
ITEM_ID = '4051.5720.27.001'
REV = '00'


def create_transport():
    """Transport should be passed in all requests, because it has information about session"""
    transport = Transport_decoration_free(session=Session())
    return transport

def get_session_client(transport):
    """Session client will used for logging in and out """
    service = 'Core-2006-03-Session'
    url = '%s/%s?wsdl' % (TC_HOST, service)
    return Client(url, transport=transport)

def login(session_client):
    response = session_client.service.login(username=TC_LOGIN, password=TC_PASSWORD, group="",  \
role="", sessionDiscriminator="1i52")
    print('> Login response object:', type(response))
    # file = open('response_login.py', 'w')
    # file.write(str(response))
    return session_client

def logout(session_client):
    session_client.service.logout()
    print('> Logged out')

def set_policy(transport):
    service = 'Core-2007-01-Session'
    url = '%s/%s?wsdl' % (TC_HOST, service)
    client = Client(url, transport=transport)
    policy_name = "DEFAULT"
    response = client.service.setObjectPropertyPolicy(policy_name)
    print('> Setting up policy to %s:' % policy_name, response)

def get_item_from_id(transport, item_id, rev_id):
    service = 'Core-2007-01-DataManagement'
    url = '%s/%s?wsdl' % (TC_HOST, service)
    client = Client(url, transport=transport)
    response = client.service.getItemFromId(nRev=1, infos={'itemId':item_id, 'revIds':rev_id}, pref='')
    print('> getItemFromId response object:', type(response))
    revision_uid = response['output'][0]['itemRevOutput'][0]['itemRevision']['uid']
    print("> Das ist die UID der Revision:", revision_uid)
    # file = open('response_getItemFromID.py', 'w')
    # file.write(str(response))
    

class Transport_decoration_free(Transport):
    def post_xml(self, address, envelope, headers):
        message = etree.tostring(envelope, pretty_print=False, xml_declaration=False, encoding="utf-8")
        return self.post(address, message, headers)


def main():
    transport = create_transport()
    session_client = get_session_client(transport)
    login(session_client)
    set_policy(transport)
    get_item_from_id(transport, ITEM_ID, REV)
    logout(session_client)


if __name__ == '__main__':
    main()
```

For me the output looks like this: 
```
> Login response object: <class 'zeep.objects.LoginResponse'>
> Setting up policy to DEFAULT: True
> getItemFromId response object: <class 'zeep.objects.GetItemFromIdResponse'>
> Das ist die UID der Revision: 3lU5AteaojgGRC
> Logged out
```

Hope it will help.

**Comment by BernsiD** [comment]
Hi Dmitry,
Thank you. This doesn't work for me either, but i think it is more likely it has something to do with my environment. Maybe some security setting is keeping the transport from getting to the next soa request. Thank you for your time and effort  helping me. I think it's just a little thing i don't see thats keeping me from getting this to work. But i will and i think your solution is great. Best Regards Bernhard

**Comment by BernsiD** [comment]
Hi Dmitry,

I setup an fresh TC-environment now the zeep implementation works fine. I will try to find out what is blocking the other TC-environment from getting the transport to the other soa requests. Thank you again for your great solution and Happy Holidays. Best Regards Bernhard

**Comment by spalk** [comment]
Hi Bernhard,
I'm glad hear it. Happy Holidays and frohe Weihnachten for you too.

**Pull request merged**
